name: CI Pipeline Auth Microservice
on:
    pull_request:
        branches:
          - staging
          - main
    push:
        branches:
          - staging
          - main

jobs:
    test:
        runs-on: ubuntu-latest
        name: Setup, test, and build project
        env:
            PORT: 50051
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build application
              run: 
                echo "Run command to build the application if present"
                npm run build